
#
# This LookML file was generated by AtScale on 2024-06-05T17:41:08.273726504Z
#
# AtScale version: C2024.1.0
# Catalog: 2Sales Insights - BigQuery_22d2e2velop4412222

connection: "Connection 2"
label: "2Sales Insights - BigQuery_22d2e2velop4412222"


include: "/views/2Sales_Insights_-_BigQuery__22d2e2velop4412222/Internet_Sales.view.lkml"


explore: Internet_Sales {
  label: "Internet Sales"
}

