
#
# This LookML file was generated by AtScale on 2025-06-04T18:57:52.338259381Z
#
# AtScale version: C2024.8.0
# Catalog: adventure-small-sml_main

connection: "looker"
label: "adventure-small-sml_main"


include: "/views/adventure-small-sml_main/ASAdventureSmall.view.lkml"

include: "/views/adventure-small-sml_main/ResellerPerspective.view.lkml"


explore: ASAdventureSmall {
  label: "ASAdventureSmall"
}

explore: ResellerPerspective {
  label: "ResellerPerspective"
}

