
#
# This LookML file was generated by AtScale on 2024-08-26T17:16:13.635346293Z
#
# AtScale version: C2024.8.0
# Catalog: AdventureWorksDW2012Multidimensional-Handmade_main

connection: "conn1"
label: "AdventureWorksDW2012Multidimensional-Handmade_main"


include: "/views/AdventureWorksDW2012Multidimensional-Handmade__main/ASAdventureSmall.view.lkml"


explore: ASAdventureSmall {
  label: "ASAdventureSmall"
}

