
#
# This LookML file was generated by AtScale on 2024-12-26T14:53:13.601905136Z
#
# AtScale version: C2024.8.0
# Catalog: Sales Insights - BigQuery_develop141312

connection: "looker-1"
label: "Sales Insights - BigQuery_develop141312"


include: "/views/Sales_Insights_-_BigQuery_develop141312/Internet_Sales.view.lkml"


explore: Internet_Sales {
  label: "Internet Sales"
}

