
#
# This LookML file was generated by AtScale on 2024-06-05T14:40:09.846197297Z
#
# AtScale version: C2024.1.0
# Catalog: Sales Insights - BigQuery_develop223

connection: "Connection 2"
label: "Sales Insights - BigQuery_develop223"


include: "/views/Sales_Insights_-_BigQuery__develop223/Internet_Sales.view.lkml"


explore: Internet_Sales {
  label: "Internet Sales"
}

