
#
# This LookML file was generated by AtScale on 2024-06-05T17:20:01.929000835Z
#
# AtScale version: C2024.1.0
# Catalog: Sales Insights - BigQuery_deve2lop223

connection: "Connection 2"
label: "Sales Insights - BigQuery_deve2lop223"


include: "/views/Sales_Insights_-_BigQuery__deve2lop223/Internet_Sales.view.lkml"


explore: Internet_Sales {
  label: "Internet Sales"
}

