
#
# This LookML file was generated by AtScale on 2024-06-05T17:31:03.863494794Z
#
# AtScale version: C2024.1.0
# Catalog: Sales Insights - BigQuery_develop4412

connection: "Connection 2"
label: "Sales Insights - BigQuery_develop4412"


include: "/views/Sales_Insights_-_BigQuery__develop4412/Internet_Sales.view.lkml"


explore: Internet_Sales {
  label: "Internet Sales"
}

