
#
# This LookML file was generated by AtScale on 2025-06-16T14:20:02.886025916Z
#
# AtScale version: C2024.8.0
# Catalog: Sales Insights_develop

connection: "looker"
label: "Sales Insights_develop"


include: "/views/Sales_Insights_develop/Internet_Sales.view.lkml"

include: "/views/Sales_Insights_develop/Internet_Sales_-_No_PII.view.lkml"


explore: Internet_Sales {
  label: "Internet Sales"
}

explore: Internet_Sales___No_PII {
  label: "Internet Sales - No PII"
}

