
#
# This LookML file was generated by AtScale on 2024-10-30T16:59:59.541071335Z
#
# AtScale version: C2024.8.0
# Catalog: Sales Insights - BigQuery_develop

connection: "partners"
label: "Sales Insights - BigQuery_develop"


include: "/views/Sales_Insights_-_BigQuery_develop/Internet_Sales.view.lkml"


explore: Internet_Sales {
  label: "Internet Sales"
}

