
#
# This LookML file was generated by AtScale on 2024-08-16T17:04:00.193203472Z
#
# AtScale version: C2024.8.0
# Catalog: Sales Insights - BigQuery_semi-additive-examples

connection: "conn1"
label: "Sales Insights - BigQuery_semi-additive-examples"


include: "/views/Sales_Insights_-_BigQuery__semi-additive-examples/Internet_Sales.view.lkml"

include: "/views/Sales_Insights_-_BigQuery__semi-additive-examples/Model-Degenerate-Dimension.view.lkml"

include: "/views/Sales_Insights_-_BigQuery__semi-additive-examples/Model-Role-Playing-Template.view.lkml"


explore: Internet_Sales {
  label: "Internet Sales"
}

explore: Model_Degenerate_Dimension {
  label: "Model-Degenerate-Dimension"
}

explore: Model_Role_Playing_Template {
  label: "Model-Role-Playing-Template"
}

