
#
# This LookML file was generated by AtScale on 2024-06-05T17:40:14.862415674Z
#
# AtScale version: C2024.1.0
# Catalog: Sales Insights - BigQuery_22d2e2velop441222

connection: "Connection 2"
label: "Sales Insights - BigQuery_22d2e2velop441222"


include: "/views/Sales_Insights_-_BigQuery__22d2e2velop441222/Internet_Sales.view.lkml"


explore: Internet_Sales {
  label: "Internet Sales"
}

