
#
# This LookML file was generated by AtScale on 2024-10-30T17:00:47.446121219Z
#
# AtScale version: C2024.8.0
# Catalog: Sales Insights - BigQuery_Julio_1

connection: "partners"
label: "Sales Insights - BigQuery_Julio_1"


include: "/views/Sales_Insights_-_BigQuery_Julio_1/Internet_Sales.view.lkml"


explore: Internet_Sales {
  label: "Internet Sales"
}

