
#
# This LookML file was generated by AtScale on 2024-12-26T14:52:50.363590666Z
#
# AtScale version: C2024.8.0
# Catalog: Sales Insights - BigQuery_develop

connection: "looker-1"
label: "Sales Insights - BigQuery_develop"


include: "/views/Sales_Insights_-_BigQuery_develop/Internet_Sales.view.lkml"


explore: Internet_Sales {
  label: "Internet Sales"
}

