
#
# This LookML file was generated by AtScale on 2024-06-05T17:35:41.910268464Z
#
# AtScale version: C2024.1.0
# Catalog: Sales Insights - BigQuery_develop44122

connection: "Connection 2"
label: "Sales Insights - BigQuery_develop44122"


include: "/views/Sales_Insights_-_BigQuery__develop44122/Internet_Sales.view.lkml"


explore: Internet_Sales {
  label: "Internet Sales"
}

