
#
# This LookML file was generated by AtScale on 2024-06-05T17:37:03.421867627Z
#
# AtScale version: C2024.1.0
# Catalog: Sales Insights - BigQuery_d2evelop44122

connection: "Connection 2"
label: "Sales Insights - BigQuery_d2evelop44122"


include: "/views/Sales_Insights_-_BigQuery__d2evelop44122/Internet_Sales.view.lkml"


explore: Internet_Sales {
  label: "Internet Sales"
}

